on:
  push:
    branches: develop
name: Development Deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    # - name: Slack notification deploy to Development
    #   uses: rtCamp/action-slack-notify@v2.0.0
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #     SLACK_USERNAME: dev-backend
    #     SLACK_CHANNEL: dev_builds
    #     SLACK_ICON: https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png
    #     SLACK_MESSAGE: '[project-template] Start deployment to development'
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Cardoc docker registry login
      run: docker login -u cardoc -p '${{ secrets.DOCKER_PASSWORD }}' registry.cardoc.co.kr
    - name: Docker build
      run: docker build -t registry.cardoc.co.kr/test/project-template/dev:latest . --build-arg COMMIT_ID=${{ github.sha }} 
    - name: Docker tagging
      run: docker tag registry.cardoc.co.kr/test/project-template/dev:latest registry.cardoc.co.kr/test/project-template/dev:${{ github.sha }}
    - name: Docker push to cardoc registry
      run: docker push --all-tags registry.cardoc.co.kr/test/project-template/dev
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.INFRA_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.INFRA_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    # - name: Deploy to k8s cluster
    #   uses: Consensys/k8s-gh-action@master
    #   env:
    #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DEV }}
    #   with:
    #     args: set image --record deployment/project-template project-template=registry.cardoc.co.kr/test/project-template/dev:${{ github.sha }} -n cardoc

    # - name: Slack notification deploy to Development
    #   uses: rtCamp/action-slack-notify@v2.0.0
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #     SLACK_USERNAME: dev-backend
    #     SLACK_CHANNEL:  dev_builds
    #     SLACK_ICON: https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png
    #     SLACK_MESSAGE: '[prject-template] Deployment ended successfully'